id: I49E49849
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T01:12:27+00:00'
last_modified: '2022-06-08T13:23:45.332974+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS17217
  title: རྡོ་རྗེ་འཇིགས་བྱེད་ཀྱི་ཞི་བའི་སྦྱིན་སྲེག་བྱ་ཚུལ་གྱི་ཆོ་ག།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '8358':
      image_group_id: I8LS17227
      title: ''
      total_pages: 56
      order: 1
      base_file: 8358.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
