id: P010411
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS17217
  title: རྡོ་རྗེ་འཇིགས་བྱེད་ཀྱི་ཞི་བའི་སྦྱིན་སྲེག་བྱ་ཚུལ་གྱི་ཆོ་ག།
  author: ''
  volumes:
    0a0ea0cbf8784c97b3389c294eaa014e:
      image_group_id: I8LS17227
      title: ''
      volume_number: 1
      total_pages: 56
